POST http://localhost:5000/api/persons
Content-Type: application/json

    {
    "number": "new number"
    }

###
POST http://localhost:5000/api/persons
Content-Type: application/json

    {
    "name": "new name"
    }

###
POST http://localhost:5000/api/persons
Content-Type: application/json

    {
    "number": "new number",
    "name": "Dan Abramov"
    }
